### ISSUE TITLE
공개키 질문

### ISSUE THREAD

**Issue by Moonachi** [LiteHell/NPKI_example#1]
혹시 공개키는 certificate.PublickKeyCertificate을 이용하여 string 문자열로 뽑아 내는 것이 맞을까요?

**Comment by LiteHell** [comment]
네

**Comment by Moonachi** [comment]
> 네

제가 전자서명을 해보고 싶어서 인증서의 개인키랑 공개키를 string 문자열로 빼내어 사용하려고 하고 있습니다.
그런데 공개키를 이용하여 암호화 할 때 에러가 발생해서 그런데 개인키, 공개키를 string 으로 추출하는 코드를 짧게 
올리면 한번 확인해주실 수 있을까요?

**Comment by LiteHell** [comment]
네, 코드 올려주시면 시간날때 확인해드리겠습니다.

**Comment by Moonachi** [comment]
정말 감사드립니다.
![image](https://user-images.githubusercontent.com/46507959/86528864-10650480-bee7-11ea-84f6-874c15ac9e92.png)
해당 코드 작성은 공인인증서 비밀번호 입력 후 바로 Console로 출력하려고 한 것입니다.
그리고 각 키 값들은 붉은색으로 동그라미 한 것으로 사용하였습니다.

계속 테스트 해보니 개인키는 맞는 것 같은데 **공개키가 문제**인 것 같습니다.

[code]
 byte[] priKey = PKCS8.PrivateKeyInfo.Encode(CertificateLoader.ConvertPrivateKeyToRSA(certificate.PrivateKeyInfo.PrivateKey));

                    Console.WriteLine("개인키");
                    Console.WriteLine("개인키 1 {0}", Encoding.UTF8.GetString(priKey));
                    Console.WriteLine("개인키 2 {0}", priKey.ToString());
                    Console.WriteLine("개인키 3 {0}", Convert.ToBase64String(priKey));

                    Console.WriteLine("공개키");
                    Console.WriteLine("공개키 1 {0}", Convert.ToBase64String(certificate.PublicKeyCertificate.GetPublicKey()));
                    Console.WriteLine("공개키 2 {0}", certificate.PublicKeyCertificate.PublicKey);

[전자서명 테스트 예제 사이트]
http://jsfiddle.net/lordloh/E5ZE4/
테스트는 js를 이용하여서 해보았습니다. openssl로 개인키, 공개키를 생성하여 테스트를 해보았는데 잘되었습니다. 그러나 제가 추출한 키로 하니 잘 되지 않아 문의드립니다.

감사합니다.

**Comment by LiteHell** [comment]
```csharp
StringBuilder builder = new StringBuilder();
builder.AppendLine("-----BEGIN CERTIFICATE-----");
builder.AppendLine(Convert.ToBase64String(certificate.PublicKeyCertificate.Export(System.Security.Cryptography.X509Certificates.X509ContentType.Cert), Base64FormattingOptions.InsertLineBreaks));
builder.AppendLine("-----END CERTIFICATE-----");

string publicKeyString = builder.ToString();
```
공개키 추출이 문제라면 공개키를 위와 같은 방법으로 다시 시도해보실 수 있으신가요?

**Comment by Moonachi** [comment]
제가 잘 되지 않아서 더 찾아보니깐 해당하는 것은 인증서 같습니다. 인증서를 바탕으로 안에 들어있는 공인키를 빼낼 수 있게 되었습니다. 감사합니다.

**Comment by Moonachi** [comment]
그런데 혹시 바로 공개키를 빼올 수 있는 방법은 없을까요? 이상하게 X509에서 말하는 것은 cert.getPublicKey를 사용하라고 하는데 해당 키는 제가 구해서 서명으로 확인한 키랑 달라서요.

위에서 말한 예시의 키 : Console.Write(certificate.PublicKeyCertificate.GetPublicKey()) 입니다. 이후 Convert.ToBase64String으로 변환하여 출력하였습니다.
참고 : https://docs.microsoft.com/ko-kr/dotnet/api/system.security.cryptography.x509certificates.x509certificate.getpublickey?view=netcore-3.1

**Comment by LiteHell** [comment]
서명으로 확인했다는 게 무슨 뜻인지 더 상세하게 설명해주실 수 있으신가요?

**Comment by Moonachi** [comment]
아 제가 말을 이상하게 했네요.

제가 이해한 것이 맞다면, 위에 올려주신 코드는 인증서 코드인 것 같습니다.
해당 인증서를 바탕으로 openssl을 이용하여 공개키를 추출하였습니다.
그리고 openssl로 암복호화 테스트를 진행해서 확인하였습니다. 

추가적으로
http://jsfiddle.net/lordloh/E5ZE4/
이전에 올렸던 사이트에서 제가 추출한 공개키, 개인키로 암복호화 되는 것을 확인하였습니다.

**Comment by LiteHell** [comment]
네, 위에 올린 코드는 인증서 코드입니다. 제가 질문을 잘못 읽어서 인증서를 추출하는 코드를 올렸습니다.
공개키를 추출하는 코드는... 추후 여유가 나는대로 올려드리겠습니다.

**Comment by Moonachi** [comment]
네 감사합니다!

**Comment by LiteHell** [comment]
```csharp
public string ExportPublicKeyAsPem(X509Certificate2 cert)
{
	RSA rsa = cert.GetRSAPublicKey();
	RSAParameters rsaParams = rsa.ExportParameters(false);
	DerSequence headerSequence = new DerSequence(new Asn1Encodable[] { new DerObjectIdentifier("1.2.840.113549.1.1.1"), DerNull.Instance });
	DerSequence pubKeySequence = new DerSequence(new Asn1Encodable[]{ new DerInteger(rsaParams.Modulus), new DerInteger(rsaParams.Exponent) });
	DerBitString pubKeyBitString = new DerBitString(pubKeySequence.GetDerEncoded());
	DerSequence sequence = new DerSequence(new Asn1Encodable[] { headerSequence, pubKeyBitString });
	byte[] derEncoded = sequence.GetDerEncoded();
	StringBuilder strBuilder = new StringBuilder();
	strBuilder.AppendLine("-----BEGIN PUBLIC KEY-----");
	strBuilder.AppendLine(Convert.ToBase64String(derEncoded, Base64FormattingOptions.InsertLineBreaks));
	strBuilder.AppendLine("-----END PUBLIC KEY-----");
	return strBuilder.ToString();
}
```
X509Certificate 인스턴스 내부의 공개키를 PKCS#1 Public Key Format에 맞춰 PEM 인코딩으로 내보내는 함수입니다. 이 함수를 아래와 같이 이용해서 쓰시면 됩니다.
```csharp
string pubKeyExported = ExportPublicKeyAsPem(certificate.PublicKeyCertificate);
```
한 번 시도해보세요.

**Comment by Moonachi** [comment]
매번 질문에 답해주셔서 감사합니다.
