### ISSUE TITLE
인증서 폐기 유무

### ISSUE THREAD

**Issue by Moonachi** [LiteHell/NPKI_example#3]
안녕하세요. 혹시 공인인증서 폐기 유무도 알 수 있을까요?
폐기된 인증서도 로그인이 되어서 문의 드립니다.

처음 table에서 뿌려줄 때 사용하는 cert 변수를 이용하여 해보려고 했는데
잘 되지 않아 다시 한번 문의 드립니다.

 -- 추가 --
X509Certificate2 함수 Verify()를 ExportPublicKeyAsPem 함수내에서 사용하였는데도
폐지된 인증서에 False가 표시됩니다.

감사합니다.

**Comment by LiteHell** [comment]
그거 CRL이나 OCSP를 이용한 국내표준이 있을텐데, 도움 될 수 있도록 시간 나는대로 코드 작성해 올려드리겠습니다.

**Comment by Moonachi** [comment]
> 그거 CRL이나 OCSP를 이용한 국내표준이 있을텐데, 도움 될 수 있도록 시간 나는대로 코드 작성해 올려드리겠습니다.

매우 감사드립니다. 제가 찾아본 것은 그냥 "인증서"인지 아닌지 판단하던 것이더라구요.
폐지되어도 인증서이긴 인증서이니 저것으로는 해결이 안되었던 것 같습니다.

매번 감사드립니다.

**Comment by LiteHell** [comment]
코드를 작성해서 올려드린다는 게 바쁘게 살다보니 까먹었네요;; [KCAC.TS.CRLPROF](https://www.rootca.or.kr/kcac/down/TechSpec/1.2-KCAC.TS.CRLPROF.pdf)를 참고하시면 큰 도움이 되지 않을까 싶습니다. 코드는... 빠른 시일내로 올릴 수 있도록 노력해볼께요, 언제가 될지는 모르겠지만.

**Comment by Moonachi** [comment]
네 매번 도움 감사합니다. 참고해보겠습니다.
