### ISSUE TITLE
공인인증서 정보 획득 문제

### ISSUE THREAD

**Issue by Moonachi** [LiteHell/NPKI_example#4]
안녕하세요. 계속 확인해보았는데 해결이 쉽게 되지 않아 문의 드립닌다.
여러 피씨에서 테스트 중 공인인증서 정보를 뿌려주는 코드 부분에서 try-catch로 묶었는데 에러가 발생하여 문의드립니다.

foreach(CertificateLocation cert in certs)
            {
                ListViewItem item = new ListViewItem();
                item.Tag = cert;
                item.Text = cert.PublicKeyCertificate.Subject;
                item.SubItems.Add(cert.PublicKeyCertificate.NotAfter.ToString());
                item.SubItems.Add(cert.LocationDescription);
                listView1.Items.Add(item);
            }

A, B PC 둘 다 동일한 인증서를 가지고 있고,
A는 되고 B는 안되고 이런 상황입니다.

catch에서 확인된 메시지는 invalid salt 입니다.
혹시 어떠한 이유 때문에 이런 경우가 발생하는지 알 수 있을까요?

**Comment by LiteHell** [comment]
정확히는 저도 잘 모르겠지만, 아마도 다른 버전의 라이브러리가 설치되면서 구현에 변화가 생겼나...라는 생각이 드는데, 한 번 확인해주실 수 있으신가요?

**Comment by Moonachi** [comment]
이게 저도 그 순간 더 깊게 봤어야 하는데 인증서를 지우고 재설치 해보니 잘 되더라구요. 같은 현상이 발견되면 다시 해보겠습니다.

추가로 혹시 해당 인증서가 '개인범용' 인지 아닌지 확인할 수 있는 방법이 있을까요? 계속 확인하고 있는데 마땅한 방법을 못 찾아서 아시면 힌트라도 주시면 감사하겠습니다.

**Comment by LiteHell** [comment]
은행인증서가 없어서... 시간 나는대로 만들어서 한번 찾아보겠습니다.

**Comment by Moonachi** [comment]
> 은행인증서가 없어서... 시간 나는대로 만들어서 한번 찾아보겠습니다.

넵. 매번 감사드립니다.

**Comment by LiteHell** [comment]
시간없어서 코드로는 작성해드릴 수 없지만 대략적으로 방법은 다음과 같습니다.
인증서 필드중에 인증서 정책(Certificate Policy) 필드의 Policy Identifier 필드 OID로 확인하시면 됩니다. [이 글](https://tough923.tistory.com/entry/%EA%B3%B5%EC%9D%B8%EC%9D%B8%EC%A6%9D%EA%B8%B0%EA%B4%80-OID-%EB%AA%A9%EB%A1%9D)의 OID 목록을 참고하시면 큰 도움이 되겠네요.

**Comment by Moonachi** [comment]
네 한번 해보겠습니다. 감사합니다.
